Build on macOS: WITH_SOAPYSDR
Fixes compile error when SoapySDR not configured. This is probably not the correct way to do it.

-- Checking for SoapySDR
-- Could NOT find SoapySDR (missing: SoapySDR_DIR)
--   SoapySDR not found
...
-- - SDR drivers:
--   - soapysdr:		requested: ON, enabled: FALSE

[100%] Linking C executable dumphfdl
Undefined symbols for architecture x86_64:
  "_soapysdr_input_vtable", referenced from:
      _input_vtables in input-common.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)