Build on macOS: LIQUID_VERSION_NUMBER
# cd build; cmake ../
...
-- Performing Test LIQUIDDSP_VERSION_CHECK
-- Performing Test LIQUIDDSP_VERSION_CHECK - Failed
CMake Error at src/CMakeLists.txt:61 (message):
  LiquidDSP library is too old or missing (min.  version required: 1.3.0)

# more CMakeFiles/CMakeError.log
Performing C SOURCE FILE Test LIQUIDDSP_VERSION_CHECK failed with the following compile output:
Change Dir: .../build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_d2d45/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_d2d45.dir/build.make CMakeFiles/cmTC_d2d45.dir/build
Building C object CMakeFiles/cmTC_d2d45.dir/src.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I/usr/local/include  -Wall -Wextra -DLIQUIDDSP_VERSION_CHECK -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15   -o CMakeFiles/cmTC_d2d45.dir/src.c.o   -c .../build/CMakeFiles/CMakeTmp/src.c
.../build/CMakeFiles/CMakeTmp/src.c:8:18: error: implicitly declaring library function 'exit' with type 'void (int) __attribute__((noreturn))' [-Werror,-Wimplicit-function-declaration]
int main(void) { LIQUID_VALIDATE_LIBVERSION return 0; }
				 ^
/usr/local/include/liquid/liquid.h:67:5: note: expanded from macro 'LIQUID_VALIDATE_LIBVERSION'
	exit(1);                                                                \
	^
.../build/CMakeFiles/CMakeTmp/src.c:8:18: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'
/usr/local/include/liquid/liquid.h:67:5: note: expanded from macro 'LIQUID_VALIDATE_LIBVERSION'
	exit(1);                                                                \
	^
1 error generated.